---

version: "2"

services:

  proxy:
    networks:
      - default
      - proxies
    restart: always

  app:
    restart: always
    user: 1000:1000
    environment:
      - HOME=/srv/http

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
    restart: always

  srcbuild:
    user: 1000:1000
    environment:
      - HOME=/srv/http

networks:
  default:
    driver: overlay
  proxies:
    external: true

