---

version: "2"

services:

  app:
    restart: always

  proxy:
    networks:
      - default
      - proxies
    restart: always

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
    restart: always

networks:
  default:
    driver: overlay
  proxies:
    external: true

