---

version: "2"

services:

  proxy:
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:my-domain.fr,static.my-domain.fr,www.my-domain.fr

  app:
    restart: always

  db:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
