version: '3'

services:
  proxy:
    image: nginx:1.23.1-alpine
    volumes:
      - ./ops/config/nginx:/etc/nginx/conf.d
    volumes_from:
      - app
    depends_on:
      - app

  app:
    build:
      dockerfile: ops/dockerfiles/app/Dockerfile
      context: .
      args:
        - user=${UID}
    user: ${UID}:${UID}
    volumes:
      - ./:/srv/http/
      - ./ops/dockerfiles/app/fpm-docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./ops/dockerfiles/app/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db

  redis:
    image: redis:7.0.4-alpine

  srcbuild:
    build:
      dockerfile: ops/dockerfiles/srcbuild/Dockerfile
      context: .
      args:
        - user=${UID}
    user: ${UID}:${UID}
    volumes_from:
      - app
    env_file: .env
    environment:
      - HOME=/srv/http

  maildev:
    image: maildev/maildev:2.0.5
    command: bin/maildev --web 80 --smtp 25 --outgoing-user test --outgoing-pass test --open --base-pathname "/maildev" --hide-extensions STARTTLS
    restart: always
