---

version: "2"

services:

  proxy:
    restart: always
    networks:
      - default
      - proxies

  app:
    restart: always

  db:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass

networks:
  default:
    driver: overlay
  proxies:
    external: true

