version: '3'

services:
  proxy:
    image: nginx:1.19.6-alpine
    volumes:
      - ./ops/config/nginx:/etc/nginx/conf.d
    volumes_from:
      - app
    depends_on:
      - app

  app:
    build:
      dockerfile: ops/dockerfiles/app/Dockerfile
      context: .
      args:
        - user=${UID}
    user: ${UID}:${UID}
    volumes:
      - ./:/srv/http/
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7.33
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
    volumes:
      - ./ops/config/mysql:/etc/mysql/conf.d

  redis:
    image: redis:6.0.10-alpine

  srcbuild:
    build:
      dockerfile: ops/dockerfiles/srcbuild/Dockerfile
      context: .
      args:
        - user=${UID}
    user: ${UID}:${UID}
    volumes_from:
      - app
    env_file: .env
    environment:
      - HOME=/srv/http

  maildev:
    image: maildev/maildev:1.1.0
    command: bin/maildev --web 80 --smtp 25 --outgoing-user test --outgoing-pass test --open
