---

version: "2"

services:

  proxy:
    image: nginx:1.9.12
    volumes:
      - ./ops/config/nginx:/etc/nginx/conf.d
    volumes_from:
      - app
    depends_on:
      - app
  
  app:
    build: ops/dockerfiles/app
    user: 1000:1000
    volumes:
      - ./:/srv/http/
    env_file: .env
    depends_on:
      - db
  
  db:
    image: mysql:5.7.8
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db

  srcbuild:
    build: ops/dockerfiles/srcbuild
    user: 1000:1000
    volumes_from: 
      - app
    env_file: .env
    environment:
      - HOME=/srv/http

  maildev:
    image: djfarrelly/maildev:0.13.0
    command: bin/maildev --web 80 --smtp 25 --outgoing-user test --outgoing-pass test --open 
